/**
 * Generated by cemu
 *
 * Architecture: %s
 *
 */

#include <unistd.h>
#include <sys/mman.h>
#include <string.h>

#define LEN %d

const char sc[LEN] = %s;

void trigger()
{
    void *sc_mapped;
    void (*func)();
    sc_mapped = mmap(NULL, LEN, PROT_READ|PROT_EXEC|PROT_WRITE, MAP_SHARED|MAP_ANONYMOUS, 0, 0);
    memcpy(sc_mapped, sc, LEN);
    func = (void (*)()) sc_mapped;
    (*func)();
    munmap(sc_mapped, LEN);
    return;
}


int main(int argc, char** argv, char** envp)
{
    trigger();
    return 0;
}