name: Publish CEmu to PyPI

on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
  publish:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    environment:
      name: hugsy
      url: https://pypi.org/p/cemu
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: "Install Pre-requisite"
        uses: eifinger/setup-rye@v4
        with:
          version: 'latest'

      - run: rye build --wheel --out ./publish

      # - name: Requirements
      #   run: |
      #     python -m pip install --upgrade build wheel

      # - name: Build
      #   run: |
      #     python -m build

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          print-hash: true
          packages-dir: publish/
