name: Publish to PyPI

on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
  publish:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    environment:
      name: hugsy
      url: https://pypi.org/p/cemu

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - uses: eifinger/setup-rye@v4
        with:
          version: 'latest'

      - run: rye build --wheel

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          print-hash: true
