name: Publish CEmu to PyPI

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Requirements
        run: |
          python -m pip install --upgrade build wheel twine

      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install (if not cached)
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          python -m pip install --user --upgrade -r requirements.txt
          python -m pip install --user --upgrade .

      - name: Build a binary wheel and source tarball
        run: |
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
